apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kafka-control-logger
  name: kafka-control-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-control-logger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-control-logger
      name: kafka-control-logger
    spec:
      containers:
      - image: ertis/kafka-ml-kafka_control_logger:v1.0  # If you want to use our builded image at Docker Hub.
    # - image: localhost:5000/kafka_control_logger       # If you want to use your local build image.
        name: kafka-control-logger
        imagePullPolicy: IfNotPresent
        env:
        - name: BOOTSTRAP_SERVERS
          value: kafka-cluster:9092
        - name: CONTROL_TOPIC
          value: control
        - name: BACKEND
          value: backend:8000