apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: tfexecutor
  name: tfexecutor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-tfexecutor
  template:
    metadata:
      labels:
        name: pod-tfexecutor
      name: tfexecutor
    spec:
      containers:
      - name: tfexecutor
        image: ertis/kafka-ml-tfexecutor:v1.0           # If you want to use our builded image at Docker Hub.
    # - image: ertis/kafka-ml-tfexecutor:v1.0-gpu       # If you want to use our builded image at Docker Hub with GPU Support.
    # - image: localhost:5000/tfexecutor                # If you want to use your local build image.
        ports:
        - containerPort: 8001
        imagePullPolicy: IfNotPresent